var myName = "David";
var myAge = 25;
var canVote = true;
var anything = "dog";
anything = 2;
document.getElementById("tsStuff-var").innerHTML = "My Name is" + myName;
document.write("canVote is a " + typeof (canVote) + "<br />");
document.write("myname is a " + typeof (myName) + "<br />");
document.write("anything is a " + typeof (anything) + "<br />");
var strToNum = parseInt("5");
var numToStr = 5;
document.write("numToStr is a " + typeof (numToStr.toString() + "<br /"));
var PI = 3.1459;
